name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: python:3.8-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
